name: Build Windows on Tag

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-win:
    name: Build Windows
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Windows package (no publish)
        # Pass --publish=never to avoid electron-builder auto-publishing on tag
        run: npm run build:win -- --publish=never

      - name: Create GitHub Release and upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/*.exe
            dist/**/*.yml
            dist/**/*.zip
            dist/**/*.blockmap
            release/**/*.exe
            release/**/*.yml
            release/**/*.zip
            release/**/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

